### ISSUE TITLE
Tag autocomplete / reinventing the add dialog?

### ISSUE THREAD

**Issue by antgel** [seeba8/yet-another-pinboard-extension#49]
Hi, thanks for this extension, the only one that leverages the API to display the user's bookmarks without having to open a new tab to Pinboard. This is a breath of fresh air! There's one thing I'd be interested in improving.

I note that when adding a new bookmark, instead of opening the pinboard add window, this extension rewrites the dlalog and then sends the data via the API. Apart from the fact that it looks a bit simple (no offence, my opinion only), it misses the cool feature of Pinboard that when you start typing a tag, it autocompletes from a list. No need to remember what all your tags are, less chance of mistyping a tag or having multiple similar tags e.g. code / coding.

Would you be interested in adding this? Would a PR from someone else be merged? Would it be better to use the pinboard add dialog rather than roll your own?

Note this is different to post tag suggestions.

Edit: Another thing that comes out of rewriting the add dialog - the UX behaviour is opposite. Pinboard has a checkbox for "Private", this extension has a checkbox for "Shared". Another reason to just use their UI?

**Comment by seeba8** [comment]
Hi @antgel 
Thanks for the feedback! I like the idea of getting the auto complete to work for the tags. Since I don't use tags very often myself, I haven't thought about that. I'll see what I can do.

I'm sceptical if it's a good idea to embed the pinboard UI to add a new bookmark since that would be an iframe and I'm not sure if that's the best thing to do in a browser web extension. And I'm not sure if that's against the pinboard guidelines or not...
That shared vs. private checkbox thing is a use case that I'm not using at all. I configured my pinboard to be private only. So this change would be lower on my priority list, but if you want to do some magic, send me a PR.  :)

Regarding PR's in general: I'm happy about people liking my addon so much that they're willing to contribute. So if the PR doesn't go against what I'm imagining in the addon, go for it!

**Comment by seeba8** [comment]
Hi @antgel, if you're up for some testing, feel free to copy the dist/ folder from the master branch, go to about:debugging#/runtime/this-firefox and load the extension as a temporary addon (probably best in a new firefox profile (about:profiles)). In the file selector, you need to select the manifest.json inside the dist/ folder.

I tried to code the tags suggestions. It shows the top 7 sorted by number of uses that start with whatever you entered.

**Comment by seeba8** [comment]
(Partly?) fixed by 44c966a

**Comment by antgel** [comment]
Completely awesome! And even more so because of my radio silence (real life kicked in for a bit). Thanks so much!
