### ISSUE TITLE
Help with using shortcuts (not working correctly?)

### ISSUE THREAD

**Issue by anaxonda** [seeba8/yet-another-pinboard-extension#51]
Hello,

Thanks for making this extension. I am having trouble using (or just understanding) the shortcuts.

Typing any of the default shortcuts ( "t", "r", "u", or "n") has no effect for me.
For example, I see that "t" is supposed to search tags. Is that supposed to work in both the action-bar, the sidebar, and the omnibar? 

Is it possible to bind a shortcut to make a new bookmark?
How about a shortcut to open the sidebar?

**Comment by seeba8** [comment]
Hi @anaxonda ,
I've recently fixed a bug / shortcoming that the prefixes don't work anywhere except in the browser address bar (e5b353952d425a9e5a72eaea7d30e3b2258f5936). This fix is not out yet since I haven't had the time to test properly it unfortunately. 

The way it works currently (despite having some bugs): in the address bar, type `pin ` (pin space), then the search prefix (e.g. t, r, u, n) then a space and then the search term you want. Once again: currently, this only works in the address bar, but as soon as I get around to testing and then publishing it, it will work in the sidebar and popup also.

> Is it possible to bind a shortcut to make a new bookmark?

As of now, no. But it's a good idea and I think it's possible to implement it. As a small consolation, you can press Alt-P to open the pinboard popup thingy.

> How about a shortcut to open the sidebar?

I was ready to answer that this is unfortunately not possible to implement, but turns out [it is](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands) and it should be rather easy to add (`_execute_sidebar_action` in the manifest file).

Maybe I will find some time to do that on Sunday. I'm always open to pull requests by the way, if you're curious to delve into web extensions.

**Comment by seeba8** [comment]
Should be fixed by 44c966a
